In [6]:
list1 = list (range(10000000))

In [7]:
%time for i in list1: i*5

Wall time: 855 ms


In [8]:
import numpy as np

In [11]:
a = np.arrange(10000000)

AttributeError: module 'numpy' has no attribute 'arrange'

In [12]:
%time a*5

NameError: name 'a' is not defined

In [13]:
z=np.zeros((2,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
z=np.zeros((3,1,9))
z

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [17]:
o = np.ones((4,6))*5
o

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

In [18]:
p= np.empty ((3,6))
p

array([[4.45057637e-308, 9.34604358e-307, 9.34605037e-307,
        1.11260483e-306, 1.78019354e-306, 4.45066125e-308],
       [9.34605037e-307, 1.60220393e-306, 1.24611674e-306,
        4.45057637e-308, 9.34597567e-307, 2.22523004e-306],
       [2.13620264e-306, 4.45063578e-308, 1.37961302e-306,
        8.45596650e-307, 5.73116149e-322, 2.22522596e-306]])

In [19]:
q = np.array ((1,2,3,4))
q

array([1, 2, 3, 4])

In [20]:
a [0,0]


NameError: name 'a' is not defined

In [21]:
a = [[[1,3],[2,4],[5,6]]]
a = np.array (a)

In [22]:
a.shape

(1, 3, 2)

In [28]:
a [0,0,0]

1

In [43]:
7*np.arange (1,11) 

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [49]:
b = ([[1,2],[2,4],[4,5]])
b

[[1, 2], [2, 4], [4, 5]]

In [50]:
b[::2]

[[1, 2], [4, 5]]

In [51]:
b[0:2]

[[1, 2], [2, 4]]

In [52]:
[11111],[10001],[10001],[10001],[11111]

([11111], [10001], [10001], [10001], [11111])

In [55]:
k=np.zeros ((5,5))
k

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
k[0]=1
k

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
k[:,0]=1
k

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [59]:
k[:,4]=1
k

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.]])

In [60]:
k[4]=1
k

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
w = np.zeros ((8,8))
w

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [91]:
w[0:8:2]=1
w

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [92]:
w.shape

(8, 8)

In [94]:
w.dtype

dtype('float64')

In [95]:
w.ndim

2

In [97]:
w.reshape (1,2)

ValueError: cannot reshape array of size 64 into shape (1,2)